// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudentBook.CoreLayer
{
    public partial class Student
    {
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string Gender { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string City { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfBirth { get; set; }
        [Column("isEnrolled")]
        public bool? IsEnrolled { get; set; }
        [Key]
        [Column("id")]
        public int Id { get; set; }
    }
}